import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { FC } from 'react';
import ProductsList from '@/components/ProductsList/ProductsList';
import { GetStaticProps } from 'next';
import axios from 'axios'
import { productsType } from '@/types/ProductsTypes';


export const getStaticProps:GetStaticProps = async () => {
  const res = await axios.get<productsType[]>('https://fakestoreapi.com/products?limit=10');
return {
  props: { products: res.data},
};
};

type ProductsTypeProps = {
  products: productsType[]
}


 const Home:FC<ProductsTypeProps> = ({products}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ProductsList products={products} />
      </div>
    </>
  )
}

export default Home
